# Generated by Django 4.1.3 on 2022-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("titles", models.PositiveIntegerField(null=True)),
                ("head_coach", models.CharField(max_length=255)),
                ("captain", models.CharField(max_length=255)),
                ("top_scorer", models.CharField(max_length=255)),
                ("fifa_code", models.CharField(max_length=3, unique=True)),
                ("last_title_at", models.DateField(null=True)),
                ("founded_at", models.DateField(null=True)),
            ],
        ),
    ]
