# Generated by Django 4.1.3 on 2022-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='head_coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_title_at',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='top_scorer',
            field=models.CharField(max_length=50),
        ),
    ]
