# Generated by Django 4.1.3 on 2022-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_team_captain_remove_team_head_coach_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="titles",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
